CREATE TABLE `hourly_weather` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`trip_id` integer NOT NULL,
	`latitude` real NOT NULL,
	`longitude` real NOT NULL,
	`date` text NOT NULL,
	`time` text NOT NULL,
	`temperature_2m` real,
	`apparent_temperature` real,
	`temperature_80m` real,
	`temperature_120m` real,
	`temperature_180m` real,
	`weather_code` integer,
	`pressure_msl` real,
	`surface_pressure` real,
	`cloud_cover` real,
	`cloud_cover_low` real,
	`cloud_cover_mid` real,
	`cloud_cover_high` real,
	`visibility` real,
	`evapotranspiration` real,
	`et0_fao_evapotranspiration` real,
	`relative_humidity_2m` real,
	`dew_point_2m` real,
	`vapour_pressure_deficit` real,
	`precipitation_probability` real,
	`precipitation` real,
	`rain` real,
	`showers` real,
	`snowfall` real,
	`snow_depth` real,
	`wind_speed_10m` real,
	`wind_speed_80m` real,
	`wind_speed_120m` real,
	`wind_speed_180m` real,
	`wind_direction_10m` integer,
	`wind_direction_80m` integer,
	`wind_direction_120m` integer,
	`wind_direction_180m` integer,
	`wind_gusts_10m` real,
	`soil_temperature_0cm` real,
	`soil_temperature_6cm` real,
	`soil_temperature_18cm` real,
	`soil_temperature_54cm` real,
	`soil_moisture_0_to_1cm` real,
	`soil_moisture_1_to_3cm` real,
	`soil_moisture_3_to_9cm` real,
	`soil_moisture_9_to_27cm` real,
	`soil_moisture_27_to_81cm` real,
	`fetched_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`trip_id`) REFERENCES `fishing_trips`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `trip_time_idx` ON `hourly_weather` (`trip_id`,`time`);--> statement-breakpoint
CREATE INDEX `user_date_idx` ON `fishing_trips` (`user_id`,`trip_date`);