PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_daily_weather` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`latitude` real NOT NULL,
	`longitude` real NOT NULL,
	`date` text NOT NULL,
	`weather_code` integer,
	`temperature_max` real,
	`temperature_min` real,
	`temperature_mean` real,
	`apparent_temperature_max` real,
	`apparent_temperature_min` real,
	`apparent_temperature_mean` real,
	`wind_speed_max` real,
	`wind_speed_mean` real,
	`wind_speed_min` real,
	`wind_gusts_max` real,
	`wind_gusts_mean` real,
	`wind_gusts_min` real,
	`wind_direction_dominant` integer,
	`shortwave_radiation_sum` real,
	`et0_fao_evapotranspiration` real,
	`et0_fao_evapotranspiration_sum` real,
	`sunshine_duration` real,
	`daylight_duration` real,
	`uv_index_max` real,
	`uv_index_clear_sky_max` real,
	`precipitation_probability_max` real,
	`precipitation_probability_min` real,
	`precipitation_probability_mean` real,
	`precipitation_hours` real,
	`precipitation_sum` real,
	`showers_sum` real,
	`rain_sum` real,
	`snowfall_sum` real,
	`snowfall_water_equivalent_sum` real,
	`pressure_msl_min` real,
	`pressure_msl_max` real,
	`pressure_msl_mean` real,
	`surface_pressure_mean` real,
	`surface_pressure_min` real,
	`surface_pressure_max` real,
	`cloud_cover_mean` real,
	`cloud_cover_max` real,
	`cloud_cover_min` real,
	`relative_humidity_mean` real,
	`relative_humidity_min` real,
	`relative_humidity_max` real,
	`dew_point_mean` real,
	`dew_point_min` real,
	`dew_point_max` real,
	`wet_bulb_temperature_max` real,
	`wet_bulb_temperature_mean` real,
	`wet_bulb_temperature_min` real,
	`vapour_pressure_deficit_max` real,
	`leaf_wetness_probability_mean` real,
	`cape_mean` real,
	`cape_max` real,
	`cape_min` real,
	`growing_degree_days_base_0_limit_50` real,
	`visibility_mean` real,
	`visibility_min` real,
	`visibility_max` real,
	`updraft_max` real,
	`sunrise` text,
	`sunset` text,
	`fetched_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
INSERT INTO `__new_daily_weather`("id", "latitude", "longitude", "date", "weather_code", "temperature_max", "temperature_min", "temperature_mean", "apparent_temperature_max", "apparent_temperature_min", "apparent_temperature_mean", "wind_speed_max", "wind_speed_mean", "wind_speed_min", "wind_gusts_max", "wind_gusts_mean", "wind_gusts_min", "wind_direction_dominant", "shortwave_radiation_sum", "et0_fao_evapotranspiration", "et0_fao_evapotranspiration_sum", "sunshine_duration", "daylight_duration", "uv_index_max", "uv_index_clear_sky_max", "precipitation_probability_max", "precipitation_probability_min", "precipitation_probability_mean", "precipitation_hours", "precipitation_sum", "showers_sum", "rain_sum", "snowfall_sum", "snowfall_water_equivalent_sum", "pressure_msl_min", "pressure_msl_max", "pressure_msl_mean", "surface_pressure_mean", "surface_pressure_min", "surface_pressure_max", "cloud_cover_mean", "cloud_cover_max", "cloud_cover_min", "relative_humidity_mean", "relative_humidity_min", "relative_humidity_max", "dew_point_mean", "dew_point_min", "dew_point_max", "wet_bulb_temperature_max", "wet_bulb_temperature_mean", "wet_bulb_temperature_min", "vapour_pressure_deficit_max", "leaf_wetness_probability_mean", "cape_mean", "cape_max", "cape_min", "growing_degree_days_base_0_limit_50", "visibility_mean", "visibility_min", "visibility_max", "updraft_max", "sunrise", "sunset", "fetched_at") SELECT "id", "latitude", "longitude", "date", "weather_code", "temperature_max", "temperature_min", "temperature_mean", "apparent_temperature_max", "apparent_temperature_min", "apparent_temperature_mean", "wind_speed_max", "wind_speed_mean", "wind_speed_min", "wind_gusts_max", "wind_gusts_mean", "wind_gusts_min", "wind_direction_dominant", "shortwave_radiation_sum", "et0_fao_evapotranspiration", "et0_fao_evapotranspiration_sum", "sunshine_duration", "daylight_duration", "uv_index_max", "uv_index_clear_sky_max", "precipitation_probability_max", "precipitation_probability_min", "precipitation_probability_mean", "precipitation_hours", "precipitation_sum", "showers_sum", "rain_sum", "snowfall_sum", "snowfall_water_equivalent_sum", "pressure_msl_min", "pressure_msl_max", "pressure_msl_mean", "surface_pressure_mean", "surface_pressure_min", "surface_pressure_max", "cloud_cover_mean", "cloud_cover_max", "cloud_cover_min", "relative_humidity_mean", "relative_humidity_min", "relative_humidity_max", "dew_point_mean", "dew_point_min", "dew_point_max", "wet_bulb_temperature_max", "wet_bulb_temperature_mean", "wet_bulb_temperature_min", "vapour_pressure_deficit_max", "leaf_wetness_probability_mean", "cape_mean", "cape_max", "cape_min", "growing_degree_days_base_0_limit_50", "visibility_mean", "visibility_min", "visibility_max", "updraft_max", "sunrise", "sunset", "fetched_at" FROM `daily_weather`;--> statement-breakpoint
DROP TABLE `daily_weather`;--> statement-breakpoint
ALTER TABLE `__new_daily_weather` RENAME TO `daily_weather`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE TABLE `__new_hourly_weather` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`latitude` real NOT NULL,
	`longitude` real NOT NULL,
	`date` text NOT NULL,
	`time` text NOT NULL,
	`temperature_2m` real,
	`apparent_temperature` real,
	`temperature_80m` real,
	`temperature_120m` real,
	`temperature_180m` real,
	`weather_code` integer,
	`pressure_msl` real,
	`surface_pressure` real,
	`cloud_cover` real,
	`cloud_cover_low` real,
	`cloud_cover_mid` real,
	`cloud_cover_high` real,
	`visibility` real,
	`evapotranspiration` real,
	`et0_fao_evapotranspiration` real,
	`relative_humidity_2m` real,
	`dew_point_2m` real,
	`vapour_pressure_deficit` real,
	`precipitation_probability` real,
	`precipitation` real,
	`rain` real,
	`showers` real,
	`snowfall` real,
	`snow_depth` real,
	`wind_speed_10m` real,
	`wind_speed_80m` real,
	`wind_speed_120m` real,
	`wind_speed_180m` real,
	`wind_direction_10m` integer,
	`wind_direction_80m` integer,
	`wind_direction_120m` integer,
	`wind_direction_180m` integer,
	`wind_gusts_10m` real,
	`soil_temperature_0cm` real,
	`soil_temperature_6cm` real,
	`soil_temperature_18cm` real,
	`soil_temperature_54cm` real,
	`soil_moisture_0_to_1cm` real,
	`soil_moisture_1_to_3cm` real,
	`soil_moisture_3_to_9cm` real,
	`soil_moisture_9_to_27cm` real,
	`soil_moisture_27_to_81cm` real,
	`fetched_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
INSERT INTO `__new_hourly_weather`("id", "latitude", "longitude", "date", "time", "temperature_2m", "apparent_temperature", "temperature_80m", "temperature_120m", "temperature_180m", "weather_code", "pressure_msl", "surface_pressure", "cloud_cover", "cloud_cover_low", "cloud_cover_mid", "cloud_cover_high", "visibility", "evapotranspiration", "et0_fao_evapotranspiration", "relative_humidity_2m", "dew_point_2m", "vapour_pressure_deficit", "precipitation_probability", "precipitation", "rain", "showers", "snowfall", "snow_depth", "wind_speed_10m", "wind_speed_80m", "wind_speed_120m", "wind_speed_180m", "wind_direction_10m", "wind_direction_80m", "wind_direction_120m", "wind_direction_180m", "wind_gusts_10m", "soil_temperature_0cm", "soil_temperature_6cm", "soil_temperature_18cm", "soil_temperature_54cm", "soil_moisture_0_to_1cm", "soil_moisture_1_to_3cm", "soil_moisture_3_to_9cm", "soil_moisture_9_to_27cm", "soil_moisture_27_to_81cm", "fetched_at") SELECT "id", "latitude", "longitude", "date", "time", "temperature_2m", "apparent_temperature", "temperature_80m", "temperature_120m", "temperature_180m", "weather_code", "pressure_msl", "surface_pressure", "cloud_cover", "cloud_cover_low", "cloud_cover_mid", "cloud_cover_high", "visibility", "evapotranspiration", "et0_fao_evapotranspiration", "relative_humidity_2m", "dew_point_2m", "vapour_pressure_deficit", "precipitation_probability", "precipitation", "rain", "showers", "snowfall", "snow_depth", "wind_speed_10m", "wind_speed_80m", "wind_speed_120m", "wind_speed_180m", "wind_direction_10m", "wind_direction_80m", "wind_direction_120m", "wind_direction_180m", "wind_gusts_10m", "soil_temperature_0cm", "soil_temperature_6cm", "soil_temperature_18cm", "soil_temperature_54cm", "soil_moisture_0_to_1cm", "soil_moisture_1_to_3cm", "soil_moisture_3_to_9cm", "soil_moisture_9_to_27cm", "soil_moisture_27_to_81cm", "fetched_at" FROM `hourly_weather`;--> statement-breakpoint
DROP TABLE `hourly_weather`;--> statement-breakpoint
ALTER TABLE `__new_hourly_weather` RENAME TO `hourly_weather`;--> statement-breakpoint
CREATE UNIQUE INDEX `time_idx` ON `hourly_weather` (`time`);