export interface WeatherData {
	date: Date;
	weatherCode: number;
	// Temperature
	temperatureMax: number;
	temperatureMin: number;
	temperatureMean: number;
	apparentTemperatureMax: number;
	apparentTemperatureMin: number;
	apparentTemperatureMean: number;
	// Wind
	windSpeedMax: number;
	windSpeedMean: number;
	windSpeedMin: number;
	windGustsMax: number;
	windGustsMean: number;
	windGustsMin: number;
	windDirectionDominant: number;
	// Solar radiation and sunshine
	shortwaveRadiationSum: number;
	et0FaoEvapotranspiration: number;
	et0FaoEvapotranspirationSum: number;
	sunshineDuration: number;
	daylightDuration: number;
	// UV Index
	uvIndexMax: number;
	uvIndexClearSkyMax: number;
	// Precipitation
	precipitationProbabilityMax: number;
	precipitationProbabilityMin: number;
	precipitationProbabilityMean: number;
	precipitationHours: number;
	precipitationSum: number;
	showersSum: number;
	rainSum: number;
	snowfallSum: number;
	snowfallWaterEquivalentSum: number;
	// Pressure
	pressureMslMin: number;
	pressureMslMax: number;
	pressureMslMean: number;
	surfacePressureMean: number;
	surfacePressureMin: number;
	surfacePressureMax: number;
	// Cloud cover
	cloudCoverMean: number;
	cloudCoverMax: number;
	cloudCoverMin: number;
	// Humidity and dew point
	relativeHumidityMean: number;
	relativeHumidityMin: number;
	relativeHumidityMax: number;
	dewPointMean: number;
	dewPointMin: number;
	dewPointMax: number;
	// Wet bulb temperature
	wetBulbTemperatureMax: number;
	wetBulbTemperatureMean: number;
	wetBulbTemperatureMin: number;
	// Vapor pressure deficit
	vapourPressureDeficitMax: number;
	// Leaf wetness
	leafWetnessProbabilityMean: number;
	// CAPE
	capeMean: number;
	capeMax: number;
	capeMin: number;
	// Growing degree days
	growingDegreeDaysBase0Limit50: number;
	// Visibility
	visibilityMean: number;
	visibilityMin: number;
	visibilityMax: number;
	// Updraft
	updraftMax: number;
	// Timestamps
	sunrise: Date;
	sunset: Date;
}

export interface OpenMeteoResponse {
	latitude: number;
	longitude: number;
	timezone: string;
	timezone_abbreviation: string;
	utc_offset_seconds: number;
	daily: {
		time: string[];
		weather_code: number[];
		temperature_2m_max: number[];
		temperature_2m_min: number[];
		temperature_2m_mean: number[];
		apparent_temperature_max: number[];
		apparent_temperature_min: number[];
		apparent_temperature_mean: number[];
		wind_speed_10m_max: number[];
		wind_speed_10m_mean: number[];
		wind_speed_10m_min: number[];
		wind_gusts_10m_max: number[];
		wind_gusts_10m_mean: number[];
		wind_gusts_10m_min: number[];
		wind_direction_10m_dominant: number[];
		shortwave_radiation_sum: number[];
		et0_fao_evapotranspiration: number[];
		et0_fao_evapotranspiration_sum: number[];
		sunshine_duration: number[];
		daylight_duration: number[];
		uv_index_max: number[];
		uv_index_clear_sky_max: number[];
		precipitation_probability_max: number[];
		precipitation_probability_min: number[];
		precipitation_probability_mean: number[];
		precipitation_hours: number[];
		precipitation_sum: number[];
		showers_sum: number[];
		rain_sum: number[];
		snowfall_sum: number[];
		snowfall_water_equivalent_sum: number[];
		pressure_msl_min: number[];
		pressure_msl_max: number[];
		pressure_msl_mean: number[];
		surface_pressure_mean: number[];
		surface_pressure_min: number[];
		surface_pressure_max: number[];
		cloud_cover_mean: number[];
		cloud_cover_max: number[];
		cloud_cover_min: number[];
		relative_humidity_2m_mean: number[];
		relative_humidity_2m_min: number[];
		relative_humidity_2m_max: number[];
		dew_point_2m_mean: number[];
		dew_point_2m_min: number[];
		dew_point_2m_max: number[];
		wet_bulb_temperature_2m_max: number[];
		wet_bulb_temperature_2m_mean: number[];
		wet_bulb_temperature_2m_min: number[];
		vapour_pressure_deficit_max: number[];
		leaf_wetness_probability_mean: number[];
		cape_mean: number[];
		cape_max: number[];
		cape_min: number[];
		growing_degree_days_base_0_limit_50: number[];
		visibility_mean: number[];
		visibility_min: number[];
		visibility_max: number[];
		updraft_max: number[];
		sunrise: string[];
		sunset: string[];
	};
}
